// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | open | /login?redirect_url=https%3A%2F%2Fwww.w3schools.com%2Fcss%2F | 
    driver.Navigate().GoToUrl("https://profile.w3schools.com/login?redirect_url=https%3A%2F%2Fwww.w3schools.com%2Fcss%2F");
    // 2 | setWindowSize | 759x769 | 
    driver.Manage().Window.Size = new System.Drawing.Size(759, 769);
    // 3 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 4 | type | name=email | singh@gmial.com
    driver.FindElement(By.Name("email")).SendKeys("singh@gmial.com");
    // 5 | click | name=password | 
    driver.FindElement(By.Name("password")).Click();
    // 6 | click | name=email | 
    driver.FindElement(By.Name("email")).Click();
    // 7 | type | name=email | singh@gmail.com
    driver.FindElement(By.Name("email")).SendKeys("singh@gmail.com");
    // 8 | click | name=password | 
    driver.FindElement(By.Name("password")).Click();
    // 9 | type | name=password | 123
    driver.FindElement(By.Name("password")).SendKeys("123");
    // 10 | click | css=.LoginForm_login_button__B4Ksc | 
    driver.FindElement(By.CssSelector(".LoginForm_login_button__B4Ksc")).Click();
    // 11 | mouseOver | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt | 
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 12 | mouseOut | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 13 | mouseOver | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt | 
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 14 | mouseOut | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) > .LoginPanel_provider_text__R-NWt | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 15 | click | css=a:nth-child(2) > .bi-x > path | 
    driver.FindElement(By.CssSelector("a:nth-child(2) > .bi-x > path")).Click();
    // 16 | click | linkText=Sign Up | 
    driver.FindElement(By.LinkText("Sign Up")).Click();
    // 17 | mouseOver | css=.LoginPanel_social_login_button__N4C-u:nth-child(1) > .LoginPanel_provider_logo__HhGpp | 
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(1) > .LoginPanel_provider_logo__HhGpp"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 18 | mouseOut | css=.LoginPanel_social_login_button__N4C-u:nth-child(1) > .LoginPanel_provider_logo__HhGpp | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 19 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(1) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(1)")).Click();
    // 20 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(1) | singh@gmail.com
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(1)")).SendKeys("singh@gmail.com");
    // 21 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | qwerty
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).SendKeys("qwerty");
    // 22 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(3) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(3)")).Click();
    // 23 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(3) | tanya
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(3)")).SendKeys("tanya");
    // 24 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(4) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(4)")).Click();
    // 25 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(4) | singh
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(4)")).SendKeys("singh");
    // 26 | click | css=.CustomButton_button__V5-G\+ | 
    driver.FindElement(By.CssSelector(".CustomButton_button__V5-G\\+")).Click();
    // 27 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).Click();
    // 28 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | Qerty
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).SendKeys("Qerty");
    // 29 | click | css=.CustomButton_button__V5-G\+ | 
    driver.FindElement(By.CssSelector(".CustomButton_button__V5-G\\+")).Click();
    // 30 | mouseOver | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) | 
    {
      var element = driver.FindElement(By.CssSelector(".LoginPanel_social_login_button__N4C-u:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 31 | mouseOut | css=.LoginPanel_social_login_button__N4C-u:nth-child(4) | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 32 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).Click();
    // 33 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | Qerty@9
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).SendKeys("Qerty@9");
    // 34 | click | css=.CustomButton_button__V5-G\+ | 
    driver.FindElement(By.CssSelector(".CustomButton_button__V5-G\\+")).Click();
    // 35 | click | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | 
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).Click();
    // 36 | type | css=.SignUpForm_signup_input__6r1Lr:nth-child(2) | Qerty@998
    driver.FindElement(By.CssSelector(".SignUpForm_signup_input__6r1Lr:nth-child(2)")).SendKeys("Qerty@998");
    // 37 | click | css=.CustomButton_button__V5-G\+ | 
    driver.FindElement(By.CssSelector(".CustomButton_button__V5-G\\+")).Click();
    // 38 | click | css=button:nth-child(5) | 
    driver.FindElement(By.CssSelector("button:nth-child(5)")).Click();
    // 39 | click | css=.LoginPanel_login_signup__N4spj | 
    driver.FindElement(By.CssSelector(".LoginPanel_login_signup__N4spj")).Click();
    // 40 | click | linkText=Next ❯ | 
    driver.FindElement(By.LinkText("Next ❯")).Click();
    // 41 | mouseOver | linkText=HOW TO | 
    {
      var element = driver.FindElement(By.LinkText("HOW TO"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 42 | mouseOver | linkText=PHP | 
    {
      var element = driver.FindElement(By.LinkText("PHP"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
